# install.packages('less')
# install.packages('GET')
# install.packages("remotes")
# remotes::install_github("forestgeo/bciex")
# install.packages('spatstat')

library(GET)
library(spatstat)
library(bciex)

load('bci.tree8.rdata')
soil_data <- read.csv('bci.soil.csv')

window <- owin(xrange = c(0, 1000), yrange=c(0,500))

bci_el <- data.frame(x=bci_elevation$x, y=bci_elevation$y, z=bci_elevation$elev)
elevation <- as.im(bci_el, W=window)

Al <- as.im(data.frame(x=soil_data$x, y=soil_data$y, z=soil_data$Al), W=window)
B <- as.im(data.frame(x=soil_data$x, y=soil_data$y, z=soil_data$B), W=window)
Ca <- as.im(data.frame(x=soil_data$x, y=soil_data$y, z=soil_data$Ca), W=window)
Cu <- as.im(data.frame(x=soil_data$x, y=soil_data$y, z=soil_data$Cu), W=window)
Fe <- as.im(data.frame(x=soil_data$x, y=soil_data$y, z=soil_data$Fe), W=window)
K <- as.im(data.frame(x=soil_data$x, y=soil_data$y, z=soil_data$K), W=window)
Mg <- as.im(data.frame(x=soil_data$x, y=soil_data$y, z=soil_data$Mg), W=window)
Mn <- as.im(data.frame(x=soil_data$x, y=soil_data$y, z=soil_data$Mn), W=window)
P <- as.im(data.frame(x=soil_data$x, y=soil_data$y, z=soil_data$P), W=window)
Zn <- as.im(data.frame(x=soil_data$x, y=soil_data$y, z=soil_data$Zn), W=window)
N <- as.im(data.frame(x=soil_data$x, y=soil_data$y, z=soil_data$N), W=window)
Nmin <- as.im(data.frame(x=soil_data$x, y=soil_data$y, z=soil_data$Nmin), W=window)
pH <- as.im(data.frame(x=soil_data$x, y=soil_data$y, z=soil_data$pH), W=window)

par(mfrow=c(5,3), mar=c(0.3,0.3,0.8,0.5))
plot(elevation, main='Elevation')
plot(Al, main='Al')
plot(B, main='B')
plot(Ca, main='CA')
plot(Cu, main='Cu')
plot(Fe, main='Fe')
plot(K, main='K')
plot(Mg, main='Mg')
plot(Mn, main='Mn')
plot(P, main='P')
plot(Zn, main='Zn')
plot(N, main='N')
plot(Nmin, main='Nmin')
plot(pH, main='pH')
